### ISSUE TITLE
logging in seems to open the artifact window right off the rip

### ISSUE THREAD

**Issue by klepp0906** [joev/SVUI-Temp#51]
except its blank/black.  only happens the first time upon logging in and only since the most recent change(s).

lmk if you need a screenie :)

**Comment by klepp0906** [comment]
245x ...ddOns\Blizzard_ArtifactUI\Blizzard_ArtifactPerks.lua:24: Usage: GetAppearanceInfoByID(artifactAppearanceID)
[C]: in function `GetAppearanceInfoByID'
...ddOns\Blizzard_ArtifactUI\Blizzard_ArtifactPerks.lua:24: in function`RefreshModel'
...ddOns\Blizzard_ArtifactUI\Blizzard_ArtifactPerks.lua:180: in function `TryRefresh'
...ddOns\Blizzard_ArtifactUI\Blizzard_ArtifactPerks.lua:81: in function <...ddOns\Blizzard_ArtifactUI\Blizzard_ArtifactPerks.lua:80>

Locals:
(*temporary) = nil

the number at the beginning (245x) kept going up until i closed the all empty/black AF window fwiw in case tha thelps.

**Comment by drveoj** [comment]
I don't think that this is SVUI because that function isn't called by any of the SVUI code... Maybe it's the fact that I've got the artifact frame in the mover... I'll remove it for now and see if that removes your issue. I'll post an update with that and with a reverse out of the talking head frame change later today.

**Comment by drveoj** [comment]
I'm uploaded changes to the artefact bar which should mean that it's highly unlikely SVUI would do this.
