### ISSUE TITLE
Bonus Roll window not appearing after fights...

### ISSUE THREAD

**Issue by DeviantJdm** [joev/SVUI-Temp#54]
Not sure if it's the UI or something else, no error pop ups or anything to go with it not appearing. :-(

**Comment by drveoj** [comment]
I'm not even sure what you mean by this @DeviantJdm - Can you explain a but more? Need to be able to reproduce the issue to track it down :)

**Comment by DeviantJdm** [comment]
The window for using a bonus roll on a boss for mythic dungeons or bosses, it did not appear on a few bosses, then suddenly started to appear again. Like i said though, no error log or lua error to go with it.

**Comment by drveoj** [comment]
I'm afraid I'm a novice about how the new dungeon system works having not played for the last 2 years so I've never even seen a Mythic dungeon :) I'll get there... once I get this darned UI sorted out once and for all (or Munglunch comes back and takes it back off my hands!)

**Comment by drveoj** [comment]
Curiouser and Curiouser. I suspected that maybe something in the skinning or frame moving might cause this so I've looked in the code and there are references to the bonus roll frame in there... however all the code relating to this are actually completely commented out! I'm guessing Munglunch was aware of a problem with it. Not sure how SVUI can be causing this since it's not actually running any code relating to it... will keep digging but would be good to know what else you're running (addon wise) so I can be sure it's  not something else/a weird inter-reaction between something else and svui

**Comment by drveoj** [comment]
Ah. And then I have to correct myself. Found the code relating to the bonus roll frame which moves it to an SVUI Alert - Will dig deeper as to why that alert isn't working.

**Comment by drveoj** [comment]
Removed the bonus-roll from being an alert (in SVUI) - I suspect alerts aren't working properly at all... I've never actually seen one! This should fix the issue but I need to fix alerts in a general sense if they're misbehaving (that's a problem for another day)
