### ISSUE TITLE
Unitframes; Rogue frames broken

### ISSUE THREAD

**Issue by Frixin** [joev/SVUI-Temp#59]
I am getting this errormessage every time i log into my rogue.
The unitframes doesnt work and the fps drops really low when i get into fight, anyone know what to do?

UnitFrames [Load]: @(09/29/16 20:35:05) - ...rames\libs\plugins\oUF_HyperCombo\oUF_HyperCombo.lua:111: attempt to index local 'cpoint' (a nil value)

**Comment by drveoj** [comment]
Have pushed a (potential) fix for this. Can you check it for me Frixin and verify? (seems fine my end)

**Comment by Frixin** [comment]
fixed that bug, another popped up! :D

UnitFrames [Load]: @(09/30/16 00:15:50) - ...rames\libs\plugins\oUF_HyperCombo\oUF_HyperCombo.lua:71: attempt to index field '?' (a nil value)

**Comment by drveoj** [comment]
Darn. I thought I'd caught them all. Just FYI: This is because the number of possible combo points is now variable because of Rogues with Anticipation... so the blizzard UI allows for a possible max of 8 but normally only sets up 5-6 for rogues and druids meaning 2-3 are not there (i.e. a nil value :>) except in special circumstances. Grrrr... Have fixed I think. Will push a change in a little bit.
