### ISSUE TITLE
Windows unmoveable

### ISSUE THREAD

**Issue by drveoj** [joev/SVUI-Temp#6]
@klepp0906 says: lots of windows arent moveable at the moment. (most notably dungeon finder & interface options window)

**Comment by klepp0906** [comment]
add achievement window to this.  (i do have overachiever addon installed but it worked prior to your update, as did dungeon window iirc.  interface options never worked since awhile back)

thank you <3

edit: add class hall mission window/artifact window (im sure your aware of alot of this if your playing as well so apologies if im being too thorough or redundant.  just a bit excited to have some of this stuff addressed!)

**Comment by drveoj** [comment]
Fixed Dungeon Finder. Can now be moved.

Achievements  is actually movable after a fashion. You can move Achievements by grabbing the frame anywhere but the top of it. I'll sort that out at some stage but given that it can be moved and there are many more things to be getting on with I'll put that on the long term fix-list :)

Class Hall and Artifact need to be skinned up but are now moveable 

From the code, InterfaceOptions is not intended to be moved (deliberately clamped in place) I don't know why exactly but I don't want to mess with it right now.
