### ISSUE TITLE
tooltip for equipped ilvl incorrect

### ISSUE THREAD

**Issue by klepp0906** [joev/SVUI-Temp#72]
no matter who i mouse over (myself included much of the time) it shows an inccorect ilvl.  went through an entire group today asking them what ilvl they saw me as and then asked them what ilvl they had equipped.  it was off by a couple each time.  not sure if this has to do with it incorrectly calculating the artifact weapons ilvl or what but i figured id' pass it on.

**Comment by drveoj** [comment]
Hi @klepp0906 - I'm not sure what you mean here. Sounds like you see some average ilvl in the tooltip?

But SVUI doesn't have an "ilvl" calculation that it puts in the unit (player, target etc.) tooltip. It only does ilvls on items in inventory and character screen (if enabled - these options can also be turned off).

I've verified that the tooltips on individual items are correct by turning off svui completely and going through every item on all of my chars, and in my bank(s) and the svui numbers and the tooltip items for ilvl match and exactly correspond with the ilvl which the default blizzard UI gives (reported through other mods like Pawn and Moncai Compare). 

If some other mod is hooking the tooltip and giving an "average ilvl" then you need to speak to them because their calculations are out. 

If that's not what you mean but that you mean individual item ilvls then:

I'm going to say that your numbers are more likely to be the correct ones. Why? Well, when you query an item's data (GetItemInfo() in the API - read here: http://wowprogramming.com/docs/api/GetItemInfo ) it uses a local cache and doesn't return the item (correctly) unless it's in the cache. 

Your equipped items are all in that cache by virtue of the fact that SVUI has been querying them (and you've been looking at them in character screen and bags etc.) but may not be in the cache of the other people viewing you. This can lead to inconsistencies depending on how their UI is getting the info about your character and items.  

I think my logic is sound but I'm happy to be corrected if you can show me how (e.g. a screenie or two?) - I'll leave the issue open awaiting your feedback but I don't think this is a bug (at present). 

BTW: Thx again for all the effort you've been putting in submitting all these issues . You've set out a great example for others by recording them and helping to unravel them. **I've added you to the official credits as a little thank you** ;)

**Comment by klepp0906** [comment]
Dead tired from a much too late night last night so I'll get you a screenshot/etc later.

Svui does have the option to show ilevel in the tooltip (average ewquipped) and much more.  U can even choose to have it show player gender, or things like spellid etc.  quite a few very helpful options.

Not on now, but when I do get on I'll find the exact section inside the control panel so u can see it yourself.

As for ilvl of inventoried items - yep, you fixed that :). TBH those "called an unprotected function" errors I was getting, haven't seen those in days either.  Your certainly getting there!

I also owe you a list of addons still I haven't forgotten.  Just between work & the new baby - time is at quite a premium, sigh. 

Adding me to the credits is very humbling - just trying to do my part in helping get this Ui back to where it was during early wod and mop.  Your doing all the heavy lifting!

**Comment by drveoj** [comment]
"Svui does have the option to show ilevel in the tooltip (average ewquipped) and much more. " 

Can you tell me where to find the option for iLevels in tooltip? I can't find it. I can only see stuff like Gender etc. in the Tooltip section and in General section (where the iLevel settings are) the iLevel settings are for character screen or bags only.

**Comment by drveoj** [comment]
@klepp0906 Ok. I've found in the code where this is... but I don't know what your discrepancy is. The tooltip contains an average iLevel provided by a built in Blizzard function. The iLevels you see on indivudual items are provided by a 3rd party library which is working fine as far as I can see (no bugs reported against it saying otherwise). 

What's the difference you're seeing? Keep in mind that the tooltip one is an average calculated not an absolute.

**Comment by klepp0906** [comment]
I think the issue is that (specially since it doesn't always happen) may be caused (cause it's always lower when it's off) by the fact that some classes have 2 artifacts persay.   

One in each hand.

The offhand one always registers as 750 regardless of the main hand one and I think it's taking this into account.  Monks for example.  Mages in fire spec (frost and arcane a staff I believe and wouldn't show this). Likely frost dk, tanks etc etc.

Not sure if that's the cause nor if it's fixable but it's likely imo.

**Comment by drveoj** [comment]
I'm still not clear what the issue is. Is the tooltip reporting your average ilevel low or high? How do you know it is? What are you basing your comment that it's " inccorect ilvl " on?

**Comment by finalsliver** [comment]
Had a few peeps in the pally order hall report their ilvl to me. It does seem to be off. 

Not by much. Maybe 7 or 8 points (people I was talking to were in their late 840's -> 850's. was getting 841 -> 845)

From what I can see, if we include the offhands (which is normal prior to legion) we get the odd value. however if we treat the main artifacts as 2handers then the value seems to come out correct.

I think Blizz may be treating these as 2h's and 'filling in' the offhand slot. which would explain the discrepancy with some classes/specs.

**Comment by klepp0906** [comment]
It's incorrect because the offhand isn't actually a separate item.  You can't level it so it would always handicap your ilvl.

Also even if that weren't the case - if you press C and view your ilvl there - it's proper, if you mouse over your player frame and view your ilvl in the tooltip, it's incorrect.  Lower.

**Comment by drveoj** [comment]
@klepp0906 Sorry. I've been impossibly dim. I hadn't understood what you meant for ages because I didn't even realise that the character screen has an character-level ilevel report (but of course it's right there on the right hand side. DOH). 

[Screenshot](http://imgur.com/a/PtT62)

What you're saying is these two don't match? If you hover over the item-level in the char screen do either of the numbers (non-equipped and equipped) match with the tooltip? 

Ultimately this is using Blizzard's own functions so if you've a bug in relation to this then it's not SVUI that's causing as it uses exactly the same function for the tooltip (equipped) item level as Blizzard do for the character screen item levels.

Have you any other addons which might try to do things with item levels? e.g. Pawn etc? (although unlikely to be Pawn as I'm using it and it is fine)

**Comment by klepp0906** [comment]
Correct.  Same for other players of a specific class/spec - their ilvl in tooltip is sometimes lower than what it actually is (if you were to ask them or use another means to ascertain such as armory or ert.

At first glance this seems to be because svui is taking the artifact offhand into account which isn't really an item at all.  As the former poster mentioned they should all be calculated as 2h with the offhand omitted which is apparently what blizzard does.

Happens on my ww monk and my fire mage which are both dual wielders so to speak.

**Comment by finalsliver** [comment]
Calculating without the offhand would make false reports of Prot warriors and Prot Paladins. both main artifacts land in the off hand slot.

I worded what I intended badly :p

**Comment by klepp0906** [comment]
Yes, DH too I believe

**Comment by drveoj** [comment]
Guys, you're flogging a dead horse here. These calculations are made by
Blizzard, not SVUI. I'm not going to change the calculation as that would
give people wrong impressions as to their gear level e.g. Eligibility for
dungeons etc. as the Blizzard number will always be used.

## 

Joe Vaughan

**Comment by klepp0906** [comment]
So why does blizzard report the right number and the svui tooltip report a different one then?  Not being combative, just curious.  Can we just get the tooltip to report the same number as the character screen?

**Comment by drveoj** [comment]
The tooltip reports equipped level. The character screen displays max Ievel
and equipped level in a tooltip if you hover over the item level in the
chat screen (sometimes but not always... don't know the conditions where
this changes but I've seen it do the opposite too)

The tooltip displays the average equipped ilevel. This is the only thing it
can report as you can't see another targets max level (as that depends on
what they have in bags which your client can't access).

## 

Joe Vaughan

**Comment by klepp0906** [comment]
Unless I'm misunderstanding you - doesn't seem to be the case for me.  When I change gear my ilvl in the character screen changes.  If it were showing max gear level that wouldn't be the case right?

I can't figure out why it's sometimes the same and sometimes different (always low never higher in tooltip fwiw) but I'll take your word for it if you say it's not fixable.

In the grand scheme - it's much less important anyhow/lower priority anyhow.

Just wondering what ilvl others see sometimes etc.  I know a lot of other Ui makers were commenting on the way dual wielding af classes got the shaft on ilvl tally but it may have been addressed.

I know your time is limited and precious as everyone's - don't let this keep ya :p
