### ISSUE TITLE
Demon Hunter buffs not showing?

### ISSUE THREAD

**Issue by finalsliver** [joev/SVUI-Temp#83]
While running around on my Vengeance Demon Hunter I noticed I had no buff timers for 'Metamorphosis' or immolation aura.

If I targeted myself I could see a counter reflecting these times accurately, but I'm not seeing any above my normal health bar, nor near my minimap.

I am seeing buffs fine on my main and my other alts.

I can also see the well-fed buff fine. 

but I can't seem to see class specific buff timers.

**Comment by finalsliver** [comment]
'Empowered Wards is showing properly on both the mini-map and the health bar buffs.

**Comment by drveoj** [comment]
Ok. Finally got to the bottom of this (and it has driven me CRAZY for 2 days solid!)  

The reason this isn't working is because somehow Blizzard filter it if you're using consolidated buffs (or HyperBuffs because they trigger consolidated buffs to the Blizz code at the same time). I don't know why but that's what seems to happen... 

From the code it looks like Munglunch started (but hadn't completed) a rewrite of Hyperbuffs and has commented out much of them (meaning they don't work in any case). 

Here's what you have to do: 

Go into SVUI Settings 

Select Auras on the left

On the Auras screen: Untick "HyperAuras Enabled" 

This will now allow Metamorphosis (and Empower Wards and Immolation Aura) to appear on the Buff Bar (beside minimap in the default layout) 

Next, select UnitFrames on the left then select "Player" 

From the dropdown on the top-right, select "Buffs" 

In the "Aura Filtering" Section, uncheck "Consolidated Buffs" (you may also have to uncheck "You can remove" if it's checked since that would filter out Metamorphosis which you can't remove :)) 

et voila! You will see your DemonHunter buffs on the buffbar and the unitframes :) 

I'm not going to fix this behaviour at present because I'm going to be moving to the latest version of oUF which will mean I'll be fixing the behaviour by setting up oUF layout to do the filtering so there's no point in doing it twice.
