### ISSUE TITLE
No Bone Shield in my buffs

### ISSUE THREAD

**Issue by TiaMaster** [joev/SVUI-Temp#89]
Please help me figure out how to get Bone Shield to show up in my player buffs.  The ones above my unitframe.

I have added "195181" to both Whitelist and Player lists, but so far nothing.  Is it considered a proc now that it is triggered by Another ability (Marrowrend)?

**Comment by finalsliver** [comment]
May be related to #83  
Fix coming soon with the integration of a new version of oUF. 

There are some suggestions for the DH buffs at the bottom of #83 from Joev which may help.

**Comment by drveoj** [comment]
Yep. I expect you'll have hyperbuffs and/or consolidated turned on. If you do consolidated then blizz (for some reason) seem to filter things like metamorphosis on DH (I guess because it's obvious when you're metamorphosed :)) so might be a similar thing. 

Hyperbuffs don't work right atm (Mung had started to rework and has commented out swathes of code relating to them). Best suggestion: Disable both. As @finalsliver says: Instructions in #83

**Comment by TiaMaster** [comment]
Fixed due to #83.
